# Whether to disable PvP when a player dies
disable-pvp-on-death: true
warning-message-enabled: true

particle-indicator:
  # Interval in ticks to show the ring of particles. 20 ticks = 1 second.
  interval-ticks: 20
  # Maximum distance (in blocks) at which players can see PvP indicators.
  max-view-distance: 32
  # The default indicator to use (must match one of the keys in the indicators section)
  default-indicator: default
  # Define multiple particle ring indicators
  indicators:
    # Default ring - red circle around feet
    default: 
    bubble_column:
      type: bubble_column_up
      points: 15
      random-particle-positions: true
      radius: 0.7
      interval: 5
      y-offset: 0.5
      random-offset-vertical: 0.25
      random-offset-horizontal: 0.0
      speed: 0.0

    cherry-tree:
      type: cherry_leaves
      points: 3
      random-particle-positions: true
      radius: 1.3
      interval: 5
      y-offset: 2.5
      random-offset-vertical: 0.25
      random-offset-horizontal: 0.2
      speed: 0

    soul:
      type: soul
      points: 12
      random-particle-positions: true
      radius: 0.3
      interval: 15
      y-offset: 0.2
      random-offset-vertical: 0.1
      random-offset-horizontal: 0.05
      speed: 0.01

    soulfire:
      type: soul_fire_flame
      points: 5
      random-particle-positions: false
      radius: 0.9
      interval: 2
      y-offset: 0.1
      random-offset-vertical: 0
      random-offset-horizontal: 0
      speed: 0.00

    lazer:
      type: trial_spawner_detection_ominous
      points: 4
      random-particle-positions: false
      radius: 0.9
      interval: 1
      y-offset: 0.2
      random-offset-vertical: 0
      random-offset-horizontal: 0
      speed: 0.0

    vault-connection:
      type: vault_connection
      points: 40
      random-particle-positions: true
      radius: 0.5
      interval: 1
      y-offset: 0.5
      random-offset-vertical: 0.3
      random-offset-horizontal: 0
      speed: 0.2

    witch:
      type: witch
      points: 16
      random-particle-positions: true
      radius: 0.8
      interval: 2
      y-offset: 0.1
      random-offset-vertical: 0.0
      random-offset-horizontal: 0
      speed: 0.0
