particle-indicator:
  # Interval in ticks to show the ring of particles. 20 ticks = 1 second.
  interval-ticks: 5

  # Particle type for the indicator (e.g., REDSTONE, FLAME, etc.)
  # If you use REDSTONE, color and size settings will be applied.
  type: REDSTONE
  # For a list of possible particles...
  # https://minecraft.wiki/w/Particles_(Java_Edition)

  # For REDSTONE particles, specify the color name.
  # Use standard Bukkit color names (e.g., RED, BLUE, GREEN).
  color: RED

  # The size (thickness) of the dust for REDSTONE particles.
  dust-size: 1.0

  # Number of points around the ring (higher = smoother circle).
  points: 32

  # Radius of the particle ring.
  radius: 0.8

  # Y-offset above the player's feet.
  y-offset: 0.1
  
  # Maximum distance (in blocks) at which players can see PvP indicators.
  max-view-distance: 32
  # As far as I can tell, players can't even see particles further than 32 blocks away.
  # I put the max limit for this value at 64 just in-case I'm wrong.
